project_id = "yqedmsoldwhkczbkxhqo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://localhost:8080",
    "https://127.0.0.1:8080",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://localhost:5173",
    "https://127.0.0.1:5173",
    "https://inboxflows-hero-glow.vercel.app"
]
jwt_expiry = 3600

[auth.external.google]
enabled = true
client_id = "929737682525-i8bguru1154i65a7geerhi0pd9qqv68l.apps.googleusercontent.com"
secret = "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"
redirect_uri = "http://localhost:8080/auth/v1/callback"

[functions]
enabled = true

[functions.fetch-gmail-leads]
verify_jwt = true
