project_id = "yqedmsoldwhkczbkxhqo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://localhost:8080",
    "https://127.0.0.1:8080"
]
jwt_expiry = 3600

[functions]
enabled = true

[functions.fetch-gmail-leads]
verify_jwt = true
