project_id = "yqedmsoldwhkczbkxhqo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
    "https://www.inboxo.co",
    "https://inboxo.co",
    "https://inboxflows-hero-glow.vercel.app",
    "http://localhost:8080"
]

[auth.external.google]
enabled = true
client_id = "929737682525-i8bguru1154i65a7geerhi0pd9qqv68l.apps.googleusercontent.com"
secret = "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"
redirect_uri = "http://localhost:8080/auth/v1/callback"
# Request offline access to get refresh tokens
url = "https://accounts.google.com/oauth/authorize?access_type=offline&prompt=consent"

[functions]
enabled = true

[functions.fetch-gmail-leads]
verify_jwt = true

[functions.scheduled-auto-sync]
verify_jwt = false
schedule = "*/5 * * * *"  # Run every 5 minutes
