// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqedmsoldwhkczbkxhqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZWRtc29sZHdoa2N6Ymt4aHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODczMzQsImV4cCI6MjA2Mzk2MzMzNH0.iQtptIKnfQkajYgvXUUQ6jOfeXkIgpd3B3TJNqVv_Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);